### PR TITLE
Fixing sort method for jQuery plugin

### PR DESCRIPTION
**Pull request by Velveeta**
Fixing sort plugin method, it lives on the Grid.prototype object, and is... being overshadowed by the this.sort instance-level object. Changing all references for the sort object from sort to sortDictionary to keep the public API consistent, and then moving some sort functionality from renderTableHeader out into its own function that can be called by both the click handler and the prototype.sort function, and fixing issues that popped up there.

### CODE REVIEW

**Comment by jhargis** [comment]
:sunglasses:  :+1:

**Comment by rstaib** [comment]
Thanks and landed in version 1.2.0 which will be publicly available in the next few days.

**Comment by rstaib** [comment]
I have recently published the release candidate (prerelease version including all features) to NPM and NuGet. Would be nice and very appreciated to get your feedback before publishing it.

**Comment by Velveeta** [comment]
I can try to take a look sometime this evening if you can tell me where to find it :)

**Comment by rstaib** [comment]
It is available on the NPM Registry, nuget.org and in the branch `fixes-and-features` [here](https://github.com/rstaib/jquery-bootgrid/tree/fixes-and-features/dist). Thanks.

**Pull request closed without merging**
